export const PUBLIC_ROUTES = {
	HOME: "",
	FREEACCHECKUP: "free-ac-checkup",
	BOOKNOW: "book-now",
	CONTACT: "contact",
	PORTFOLIO: "portfolio",
	ABOUT: "about",
	OFFERS: "offers",
	ACServicing: "services/ac-servicing",
	ACRepair: "services/ac-repairing-maintenance",
	ACInstallation: "services/ac-installation-shifting",
	ACSupply: "services/ac-supply",
	BLOGS: "blogs",
	BLOG: "blogs/:id",
	NOTFOUND: "*",
};
